### ISSUE TITLE
Publish package to pypi

### ISSUE THREAD

**Issue by awennersteen** [pasqal-io/pyqtorch#7]
for ease of installation

**Comment by Slimane33** [comment]
I am willing to do this. Are these instructions good enough ? https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56

**Comment by awennersteen** [comment]
Yeah, that should be fine. I'd also recommend reusing Pulsers code for this:
https://github.com/pasqal-io/Pulser/blob/develop/.github/workflows/publish.yml

**Comment by arthurfaria** [comment]
Hi, I also want to participate in this. In fact, I've always wondered how to create pypi packages from GitHub repositories. As discussed with @Slimane33, to make the repo pip installable, the steps are basically the following: 

1. cloning PyQ repo: `git clone https://github.com/pasqal-io/PyQ.git`
2. `cd PyQ`
3. creating a package from PyQ: `python setup.py sdist bdist_wheel`
4. `cd dist`
5. upload it to pypi : `pip install twine` -> `twine upload dist/*`
6. enter **unsername** and **password**

is there something missing?  If I am not mistaken, setup.py is already predefined with pyproject.toml, right?

**Comment by Slimane33** [comment]
@awennersteen shall we complete the `setup.py` as it is done in pulser here https://github.com/pasqal-io/Pulser/blob/develop/setup.py or all the information contained in `pyproject.toml` are enough ?

**Comment by awennersteen** [comment]
Sorry, I missed the message from you @arthurfaria 
If you were to build it manually that's exactly how to do it, however, it's better to let github handle this

@Slimane33 the pyproject contains all the needed info.
Note that when copy-pasting our internal build files Mario accidentally put
```
license = {text = "Proprietary"}
```
That should of course be changed to Apache

Since we use hatch now we only need to
```
awennersteen:~/work/pasqal/pqs/PyQ (main)$ python3 -m pip install build
(.venv) awennersteen:~/work/pasqal/pqs/PyQ (main)$ python3 -m build
```
or in github workflow language:
```
      - name: Install build dependencies
        run: pip install build
      - name: Build dist
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
 ````
 
 Where someone has to add their PYPI_API_TOKEN to the repo secrets.  I don't have those rights, but maybe Slimane does?
 if not, I'll speak to @bejito and sort it.
 
 And, similarly to pulser we should use the pypi test repo
